services:
  resolver:
    image: ghcr.io/ar-io/arns-resolver:${RESOLVER_IMAGE_TAG:-7fe02ecda2027e504248d3f3716579f60b561de5}
    build:
      context: .
    restart: on-failure
    ports:
      - ${HOST_PORT:-6000}:${CONTAINER_PORT:-6000}
    environment:
      - PORT=${CONTAINER_PORT:-6000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - IO_PROCESS_ID=${IO_PROCESS_ID:-}
      - RUN_RESOLVER=${RUN_RESOLVER:-true}
      - EVALUATION_INTERVAL_MS=${EVALUATION_INTERVAL_MS:-}
      - ARNS_CACHE_TTL_MS=${ARNS_CACHE_TTL_MS:-}
      - ARNS_CACHE_PATH=${ARNS_CACHE_PATH:-./data/arns}
      - ARNS_CACHE_TYPE=${ARNS_CACHE_TYPE:-redis}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL:-redis://redis:6379}
      - AO_CU_URL=${AO_CU_URL:-}
      - AO_MU_URL=${AO_MU_URL:-}
      - AO_GATEWAY_URL=${AO_GATEWAY_URL:-}
      - AO_GRAPHQL_URL=${AO_GRAPHQL_URL:-}
    volumes:
      - ${ARNS_CACHE_PATH:-./data/arns}:/app/data/arns
    depends_on:
      - redis

  redis:
    image: redis:${REDIS_IMAGE_TAG:-7}
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DATA_PATH:-./data/redis}:/data
      
